config/routes.rb
Rails.application.routes.draw do
  root                  "static_pages#home"
  post     "login"   =>   "sessions#create"
  get    "login"   => "sessions#new"
  delete  "logout"  =>   "sessions#destroy"
  get "signup"  => "users#new"

  resources :users
  resources :categories, only: [:index] do
    resources :lessons, only: [:new, :create, :edit, :update]
  end
  resources :results, only: :index
  resources :words, only: [:index]
  resources :relationships, only: [:create, :destroy, :show]

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :categories do
      resources :words
    end
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :results, dependent: :destroy
  has_many :answers, dependent: :destroy
  validates :category, presence: true
  validates :content, presence: true
  validates :sound, presence: true
  accepts_nested_attributes_for :answers,
    reject_if: proc {|attributes| attributes[:content].blank?}

  scope :not_in_ids, -> ids {where.not id: ids}

  scope :of_category, -> category_id do
    where category_id: category_id if category_id.present?
  end

  scope :show_all, -> user_id {}

  scope :learned, -> user_id do
    joins(results: [:lesson, :answer]).where(lessons: {user_id: user_id},
      answers: {is_correct: true})
  end

  scope :not_learned, -> user_id do
    not_in_ids(Word.learned user_id)
  end

  scope :random, ->{order("RANDOM()").limit(4)}

  class << self
    def to_csv options = {}
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |word|
          csv << word.attributes.values_at(*column_names)
        end
      end
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :login_user
  before_action :verify_admin

  def index
    @words = Word.of_category params[:category_id]
    @category = Category.find_by params[:category_id]
    respond_to do |format|
      format.html
      format.csv {send_data @words.to_csv}
      format.xls
    end
  end

  def new
    @category = Category.find_by params[:category_id]
    @word = @category.words.build
    build_answers
  end

  def create
    @category = Category.find_by params[:category_id]
    @word = @category.words.new word_params
    if @word.save
      redirect_to admin_category_words_path
    else
      build_answers
      render :new
    end
  end

  def edit
    @word = Word.find_by id: params[:id]
  end

  def update
    @word = Word.find_by id: params[:id]
    if @word.update(word_params)
      flash[:success] = I18n.t "admin.words.edit.success"
      redirect_to admin_category_words_path
    else
      flash[:danger] = I18n.t "admin.words.edit.failed"
      render :edit
    end
  end

  def destroy
    @word = Word.find_by id: params[:id]
    if Result.find_by(word_id: params[:id]).nil?
      @word.destroy
      flash[:success] = I18n.t "admin.words.delete.success"
      redirect_to admin_category_words_path
    else
      flash[:danger] = I18n.t "admin.words.delete.failed"
      @category = Category.find_by params[:category_id]
      @words = @category.words
      redirect_to admin_category_words_path
    end
  end

  private
  def build_answers
    4.times{@word.answers.build}
  end

  def word_params
    params.require(:word).permit(:content, :sound,
      answers_attributes: [:id, :content, :is_correct])
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :login_user, only: [:index, :search]

  def index
    @categories = Category.all
    params[:word_filter] ||= Settings.word_filter[:all]
    @words = Word.of_category(params[:category_id])
        .send(params[:word_filter], current_user.id)
  end
end

app/views/admin/words/_form.html.erb
<%= form_for @word, url: path do |f| %>
  <div class="col-lg-12 padding-zero">
    <%= render "shared/error_messages", object: f.object %>
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control" %>
    <%= f.label :sound %>
    <%= f.text_field :sound, class: "form-control" %>
  </div>

  <div class="col-lg-12 padding-zero">
    <%= f.fields_for :answers do |ff| %>
      <div class="col-lg-12 padding-zero margin-top-20 ">
        <%= "#{t "admin.words.answer"} #{increase_one ff
        .options[:child_index]}" %>
      </div>
      <div class="col-lg-12 padding-zero">
        <%= ff.label :content %>
      </div>
      <div class="col-lg-12 padding-zero">
        <div class="col-lg-10 padding-zero">
          <%= ff.text_field :content, class: "form-control" %>
        </div>
        <div class="col-lg-2 padding-zero">
          <%= ff.label "is_correct_true", "correct" %>
          <%= ff.radio_button :is_correct, ff.object.is_correct,
          checked: ff.object.is_correct, class: "answers" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-lg-12 text-center margin-top-20">
    <%= f.submit t("admin.words.submit"), class: "btn btn-default",
      id: "form-word" %>
  </div>
<% end %>

app/views/admin/words/edit.html.erb
<%= provide :title, t("admin.words.title") %>
<%= content_for :view_specific_css do  %>
  <%= stylesheet_link_tag "application", "static_page" %>
<% end %>
<div class="row">
  <div class="col-lg-12 padding-twenty">
    <div class="col-lg-offset-3 col-lg-6">
      <%= render "form", path:
        admin_category_word_path(params[:category_id],@word) %>
    </div>
  </div>
</div>

app/views/admin/words/index.html.erb
<%= provide :title, t("admin.words.title") %>
<%= content_for :view_specific_css do  %>
  <%= stylesheet_link_tag "application", "static_page" %>
<% end %>
<div class="row padding-top-20">
  <div class="col-lg-12 padding-top-20">
    <%= link_to t("admin.words.new"), new_admin_category_word_path,
      class: "btn btn-default box-shadow" %>
    <%= link_to t("admin.words.export_csv"),
      admin_category_words_path(format: "csv"),
      class: "btn btn-default box-shadow"  %>
    <%= link_to t("admin.words.export_xls"),
      admin_category_words_path(format: "xls"),
      class: "btn btn-default box-shadow" %>
  </div>
  <div class="col-lg-12">
    <h4 class="text-center"><%= @category.name %></h4>
  </div>
  <div class="col-lg-12">
    <table data-toggle="table"
        data-search="true"
        data-pagination="true"
        data-page-size=10
        data-page-list="[10,20,All]"
        data-height="500 "
    >
      <thead>
        <tr>
          <th><%= t "admin.words.index.stt" %></th>
          <th><%= t "admin.words.index.japanese" %></th>
          <th><%= t "admin.words.index.vietnamese" %></th>
          <th><%= t "admin.words.index.edit" %></th>
          <th><%= t "admin.words.index.delete" %></th>
        </tr>
      </thead>
      <tbody>
        <% @words.each_with_index do |word, index| %>
          <tr>
            <td><%= increase_one index %></td>
            <td><%= word.content %></td>
            <td><%= word.answers.correct.first.content %></td>
            <td>
              <%= link_to edit_admin_category_word_path(@category.id,
                word), class: "font-size-20" do %>
                <span class="glyphicon glyphicon-edit"></span>
              <% end %>
            </td>
            <td>
              <%= link_to admin_category_word_path(@category.id ,word),
                method: :delete,  data: {confirm:
                  t("admin.words.index.confirm_delete")},
                 class: "font-size-20" do %>
                <span class="glyphicon glyphicon-trash"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/words/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String"><%= t "admin.words.word.id" %></Data>
        </Cell>
        <Cell>
          <Data ss:Type="String"><%= t "admin.words.word.content" %></Data>
        </Cell>
        <Cell>
          <Data ss:Type="String"><%= t "admin.words.word.sound" %></Data>
        </Cell>
        <Cell>
          <Data ss:Type="String"><%= t "admin.words.word.category_id" %>
          </Data>
        </Cell>
      </Row>
      <% @words.each do |word| %>
        <Row>
          <Cell><Data ss:Type="Number"><%= word.id %></Data></Cell>
          <Cell><Data ss:Type="String"><%= word.content %></Data></Cell>
          <Cell><Data ss:Type="String"><%= word.sound %></Data></Cell>
          <Cell><Data ss:Type="Number"><%= word.category_id %></Data></Cell>
        </Row>
        <Row>
          <Cell></Cell>
          <Cell>
            <Data ss:Type="String"><%= t "admin.words.answer.id" %></Data>
          </Cell>
          <Cell>
            <Data ss:Type="String"><%= t "admin.words.answer.content" %></Data>
          </Cell>
          <Cell>
            <Data ss:Type="String"><%= t "admin.words.answer.is_correct"%>
            </Data>
          </Cell>
          <Cell>
            <Data ss:Type="String"><%= t "admin.words.answer.word_id" %>
            </Data>
          </Cell>
        </Row>
        <% word.answers.each do |answer| %>
          <Row>
            <Cell></Cell>
            <Cell><Data ss:Type="Number"><%= answer.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= answer.content %></Data>
            </Cell>
            <Cell>
              <Data ss:Type="String"><%= answer.is_correct.to_s %></Data>
            </Cell>
            <Cell><Data ss:Type="Number"><%= answer.word_id %></Data>
            </Cell>
          </Row>
        <% end %>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/words/new.html.erb
<%= provide :title, t("admin.words.title") %>
<%= content_for :view_specific_css do  %>
  <%= stylesheet_link_tag "application", "static_page" %>
<% end %>
<div class="row">
  <div class="col-lg-12 padding-twenty">
    <div class="col-lg-offset-3 col-lg-6">
      <%= form_for @word, url: admin_category_words_path do |f| %>
        <div class="col-lg-12 padding-zero">
          <%= render "shared/error_messages", object: f.object %>
          <%= f.label :content %>
          <%= f.text_field :content, class: "form-control" %>
          <%= f.label :sound %>
          <%= f.text_field :sound, class: "form-control" %>
        </div>

        <div class="col-lg-12 padding-zero">
          <%= f.fields_for :answers do |ff| %>
            <div class="col-lg-12 padding-zero margin-top-20 ">
              <%= "#{t "admin.words.answer"} #{increase_one ff
                .options[:child_index]}" %>
            </div>
            <div class="col-lg-12 padding-zero">
              <%= ff.label :content %>
            </div>
            <div class="col-lg-12 padding-zero">
              <div class="col-lg-10 padding-zero">
                <%= ff.text_field :content, class: "form-control" %>
              </div>
              <div class="col-lg-2 padding-zero">
                <%= ff.label "is_correct_true", "correct" %>
                <%= ff.radio_button :is_correct, true,
                  checked: false, class: "answers" %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-lg-12 text-center margin-top-20">
          <%= f.submit t("admin.words.submit"), class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
  </div>
</div>