config/routes.rb
Rails.application.routes.draw do
  root                  "static_pages#home"
  post     "login"   =>   "sessions#create"
  get    "login"   => "sessions#new"
  delete  "logout"  =>   "sessions#destroy"
  get "signup"  => "users#new"

  resources :users
  resources :categories, only: [:index] do
    resources :lessons, only: [:new, :create, :edit, :update]
  end
  resources :results, only: :index
  resources :words, only: [:index]
  resources :relationships, only: [:create, :destroy, :show]

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :categories do
      resources :words
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  attr_accessor :remember_token
  has_many :activities, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :lessons, dependent: :destroy

  validates :name,  presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}

  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  before_save :downcase_email
  has_secure_password
  scope :search, ->(keyword) {where("name LIKE ?", "%#{keyword}%")}
  default_scope {order("created_at DESC")}

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def is_user? user
      self == user
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def cookies_remember
    self.remember_token = User.new_token
    update_attribute :remember_digest, User.digest(remember_token)
  end

  def cookies_forget
    update_attribute :remember_digest, nil
  end

  def cookies_authenticated? remember_token
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :login_user, only: :show
  before_action :load_user, only: [:show, :destroy]
  before_action :verify_admin, only: [:index, :show, :destroy]

  def index
    @users = User.search(params[:search]).paginate page: params[:page],
      per_page: Settings.record_per_page
  end

  def show
  end

  def destroy
    if @user.destroy
      flash[:success] = t "dmin.index_delete.success_delete"
    else
      flash[:danger] = t "dmin.index_delete.fail_delete"
    end
    redirect_to admin_users_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_user, only: [:index, :edit, :update, :destroy]
  before_action :load_user, only: [:edit, :update, :show]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.paginate page: params[:page],
      per_page: Settings.record_per_page
  end

  def show
    if @user.nil?
      flash[:danger] = I18n.t "not_success"
      redirect_to root
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = I18n.t "signup"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = I18n.t "update_success"
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def gravatar_for_admin user, options = {size: 80}
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<input type="hidden" value="<%= @user.id %>" id="followed_id">
<input type="button" value="<%= t("follow.button_follow") %>"
 class="btn btn-primary " id="id_btn_follow" >

app/views/users/_follow_form.html.erb
<% unless current_user? @user %>
  <div id="follow_form">
  <%= render current_user.following?(@user) ? "unfollow" : "follow" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= f.submit t("update_profile.button_save"), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<input type="hidden" value="<%= @user.id %>" id="followed_id">
<input type="button" value="<%= t("follow.button_unfollow") %>"
 class="btn btn-primary" id="id_btn_follow" >

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide :title, t("update_profile.update_title") %>
<h1><%= t "update_profile.Update_page_title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank"> <%= t ("update_profile.save_change") %></a>
    </div>
</div>

app/views/users/index.html.erb
<% provide :title, t("update_profile.all_user") %>
<h1><%= t "update_profile.all_user" %></h1>
<%= will_paginate %>
  <ul class="users">
    <%= render @users %>
  </ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, t("update_profile.singup_title") %>
<%= content_for :view_specific_css do %>
  <%= stylesheet_link_tag "application", "user", "static_page" %>
<% end %>
<h1> <%= t "update_profile.title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>
     <%= render "shared/error_messages", object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :password_confirmation, t("update_profile.confirm_pass") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= f.submit t("label_submit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<%= content_for :view_specific_css do  %>
  <%= stylesheet_link_tag "application", "user", "static_page"  %>
<% end %>
<div class="row padding-twenty">
  <div class="col-lg-3 padding-zero text-center">
    <%= render "layouts/user" %>
    <h1><%= @user.name %></h1>
    <%= render "shared/stats" %>
    <%= render "follow_form" if logged_in? %>
  </div>
  <div class="col-lg-9 padding-zero">
    <div class="col-lg-12">
      <div class="col-lg-6">
        <%= link_to t("users.show.words"), words_path, class: "btn btn-primary btn-home max-width" %>
      </div>
      <div class="col-lg-6">
        <%= link_to t("category.button_lesson"), categories_path,
          class: "btn btn-primary btn-home max-width" %>
      </div>
    </div>
    <div class="col-lg-12">
      <h3><%= t "users.show.activities" %></h3>
      <hr>
    </div>
    <div class="col-lg-12">
      <% if @user.activities.any?  %>
        <ul class="list-activities">
          <% @user.activities.reverse.each do |activity| %>
            <li><%= activity.show_activity %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>