config/routes.rb
Rails.application.routes.draw do
  root                  "static_pages#home"
  post     "login"   =>   "sessions#create"
  get    "login"   => "sessions#new"
  delete  "logout"  =>   "sessions#destroy"
  get "signup"  => "users#new"

  resources :users
  resources :categories, only: [:index] do
    resources :lessons, only: [:new, :create, :edit, :update]
  end
  resources :results, only: :index
  resources :words, only: [:index]
  resources :relationships, only: [:create, :destroy, :show]

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :categories do
      resources :words
    end
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  validates :user, presence: true
  validates :category, presence: true
  has_many :results, dependent: :destroy
  has_many :words, through: :results
  accepts_nested_attributes_for :results,
    reject_if: proc {|attributes| attributes[:answer_id].blank?}

  scope :total_learned_words, -> do
    joins(results: :answer).where("answers.is_correct = 't'").count
  end

  scope :of_category, -> category_id do
    where category_id: category_id if category_id.present?
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :login_user, only: [:edit, :update]

  def new

  end

  def create
    @category = Category.find_by id: params[:category_id]
    @lesson = Lesson.create category: @category, user: current_user
    @words = @category.words.random
    if @lesson
      @words.each do |word|
        Result.create word: word, lesson: @lesson
      end
      redirect_to edit_category_lesson_path(@category.id,@lesson)
    end
  end

  def edit
    @lesson = Lesson.find_by id: params[:id]
  end

  def update
    @lesson = Lesson.find_by id: params[:id]
    if @lesson.update(lesson_params)
      redirect_to results_path lesson_id: params[:id]
    else
      flash[:danger] = t "learn_lesson.finish_failed"
      render edit_category_lesson_path
    end
  end

  private
  def lesson_params
    params.require(:lesson).permit(results_attributes: [:id, :answer_id])
  end
end

app/views/lessons/edit.html.erb
<%= provide(:title, t("learn_lesson.title")) %>
<%= content_for :view_specific_css do %>
  <%= stylesheet_link_tag "application", "static_page" %>
<% end %>
<div class="row">
  <div class="col-lg-12 padding-bottom-20">
    <h1 class="text-center">
      <%= @lesson.category.name %>
    </h1>
    <%= form_for @lesson, url: category_lesson_path do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <div class="col-lg-12 padding-left-80">
        <%= f.fields_for :results do |ff| %>
          <h5><%= increase_one ff.options[:child_index] %>.
            <%= ff.object.word.content %></h5>
          <% ff.object.word.answers.each do |answer| %>
            <div class="col-lg-12">
              <%= ff.radio_button :answer_id, answer.id, checked: false %>
              <%= ff.label "answer_id_#{answer.id}", answer.content,
              class: "font-weight-normal" %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="col-lg-12 text-center">
        <%= f.submit t("learn_lesson.finish"), class: "btn btn-default" %>
      </div>
    <% end %>
  </div>
</div>