config/routes.rb
Rails.application.routes.draw do
  root                  "static_pages#home"
  post     "login"   =>   "sessions#create"
  get    "login"   => "sessions#new"
  delete  "logout"  =>   "sessions#destroy"
  get "signup"  => "users#new"

  resources :users
  resources :categories, only: [:index] do
    resources :lessons, only: [:new, :create, :edit, :update]
  end
  resources :results, only: :index
  resources :words, only: [:index]
  resources :relationships, only: [:create, :destroy, :show]

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :categories do
      resources :words
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  attr_accessor :remember_token
  has_many :activities, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :lessons, dependent: :destroy

  validates :name,  presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}

  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  before_save :downcase_email
  has_secure_password
  scope :search, ->(keyword) {where("name LIKE ?", "%#{keyword}%")}
  default_scope {order("created_at DESC")}

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def is_user? user
      self == user
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def cookies_remember
    self.remember_token = User.new_token
    update_attribute :remember_digest, User.digest(remember_token)
  end

  def cookies_forget
    update_attribute :remember_digest, nil
  end

  def cookies_authenticated? remember_token
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  private
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :login_user, only: :show
  before_action :load_user, only: [:show, :destroy]
  before_action :verify_admin, only: [:index, :show, :destroy]

  def index
    @users = User.search(params[:search]).paginate page: params[:page],
      per_page: Settings.record_per_page
  end

  def show
  end

  def destroy
    if @user.destroy
      flash[:success] = t "dmin.index_delete.success_delete"
    else
      flash[:danger] = t "dmin.index_delete.fail_delete"
    end
    redirect_to admin_users_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_user, only: [:index, :edit, :update, :destroy]
  before_action :load_user, only: [:edit, :update, :show]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.paginate page: params[:page],
      per_page: Settings.record_per_page
  end

  def show
    if @user.nil?
      flash[:danger] = I18n.t "not_success"
      redirect_to root
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = I18n.t "signup"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = I18n.t "update_success"
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def gravatar_for_admin user, options = {size: 80}
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/admin/users/index.html.erb
<% provide :title, t("admin.index_delete.title") %>
<%= content_for :view_specific_css do  %>
  <%= stylesheet_link_tag "application", "user","static_page" %>
<% end %>
<h2><%= t "admin.index_delete.title"  %></h2>
<%= form_tag admin_users_path, method: :get do %>
  <%= text_field_tag :search, params[:search], placeholder: t("admin.index_delete.search_text"), class: "form-control"  %>
  <%= submit_tag t("admin.index_delete.bt_search"), class: "btn btn-primary"%>
<% end %>
<div class="table-responsive table-condensed">
  <table class="table">
    <thead>
      <tr>
        <th><%= t "admin.index_delete.id" %></th>
        <th><%= t "admin.index_delete.avatar" %></th>
        <th><%= t "admin.index_delete.name" %></th>
        <th><%= t "admin.index_delete.email" %></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each.with_index do |user, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= gravatar_for_admin user %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <% if current_user.is_admin? && !current_user?(user) %>
              <%= link_to t("admin.index_delete.view_user"), [:admin, user] %>|
              <%= link_to t("admin.index_delete.delete_user"), [:admin, user],
                method: :delete, data: {confirm: t("admin.index_delete.confirm_del")} %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate %>

app/views/admin/users/show.html.erb
<% provide :title, @user.name %>
<%= content_for :view_specific_css do  %>
  <%= stylesheet_link_tag "application", "user","static_page" %>
<% end %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
        <%= image_tag @user.avatar.url if @user.avatar? %>
      </h1>
    </section>
  </aside>
</div>